---
title: "plotly"
output: html_document
date: "2025-10-26"
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Let's load the data set
```{r}
data("nyc_airbnb")
nyc_airbnb=
  nyc_airbnb %>% 
  mutate(rating=review_scores_location/2) %>% 
  select(
    neighbourhood_group,neighbourhood,rating,price,room_type,lat,long
  ) %>% 
  filter(
     !is.na(rating),
    neighbourhood_group=="Manhattan",
    room_type=="Entire home/apt",
    price<=500,
    price>=100
  )
```

Lets make a scatterplot but interactive this time ! 

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```

Making a box plot 
```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

Bar chart 
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```



